Repository deckhouse/csi-ceph, pull requests merged in 2025-03, with the labels that each got.

#37 [csi] Revert root privileges enable and fix absent mounts for rbd plugin
  templates/rbd/controller.yaml
Labels: enhancement

#33 [docs] Fixed module status
  docs/README.md
  docs/README_RU.md
Labels: documentation

#41 Add metadata cleanup
  .github/workflows/build_dev.yml
  .github/workflows/build_prod.yml
  .github/workflows/deploy_dev.yml
  .github/workflows/deploy_prod.yml
  .github/workflows/dev_registry-cleanup.yml
  .github/workflows/go_lint.yaml
  .github/workflows/trivy_check.yaml
  .github/workflows/trivy_image_check.yaml
  images/controller/src/pkg/controller/ceph_cluster_authentication_watcher.go
  images/controller/src/pkg/controller/ceph_cluster_connection_watcher_func.go
  images/controller/src/pkg/controller/ceph_storage_class_watcher_func.go
  images/csi-ceph/patches/0001-fix.patch
  images/csi-ceph/werf.inc.yaml
  werf-giterminism.yaml
  werf.yaml
Labels: enhancement

#38 [internal] Fix migration from CephClusterAuthentication
  hooks/go/050-migrate-auth-to-connection/migrate-auth-to-connection.go
  hooks/go/go.mod
  hooks/go/go.sum
Labels: bug

#44 [CI] Fix runners in CI
  .github/workflows/build_dev.yml
  .github/workflows/build_prod.yml
  .github/workflows/deploy_dev.yml
  .github/workflows/deploy_prod.yml
  .github/workflows/dev_registry-cleanup.yml
Labels: enhancement

#34 [internal] Migrate from old module
  api/go.mod
  api/go.sum
  api/v1alpha1/ceph_storage_class.go
  docs/README.md
  docs/README_RU.md
  hack/generate_code.sh
  hooks/go/050-migrate-auth-to-connection/migrate-auth-to-connection.go
  hooks/go/060-migrate-from-ceph-csi-module/migrate-from-ceph-csi-module.go
  hooks/go/070-remove-finalizers-on-module-delete/remove-finalizers-on-module-delete.go
  hooks/go/api/v1alpha1/ceph_csi_driver.go
  hooks/go/api/v1alpha1/register.go
  hooks/go/api/v1alpha1/zz_generated.deepcopy.go
  hooks/go/funcs/funcs.go
  hooks/go/go.mod
  hooks/go/go.sum
  hooks/go/main.go
  images/controller/src/cmd/main.go
  images/controller/src/go.mod
  images/controller/src/go.sum
  images/controller/src/pkg/controller/ceph_storage_class_watcher.go
  images/controller/src/pkg/controller/ceph_storage_class_watcher_func.go
  images/controller/src/pkg/controller/ceph_storage_class_watcher_test.go
  images/controller/src/pkg/controller/controller_suite_test.go
  images/controller/src/pkg/internal/const.go
  images/webhooks/src/go.mod
  images/webhooks/src/go.sum
  monitoring/prometheus-rules/storage-class.yaml
  templates/controller/rbac-for-us.yaml
Labels: enhancement

#47 [docs] Add quickstart guide
  docs/README.md
  docs/README_RU.md
Labels: documentation
