Repository deckhouse/csi-ceph, pull requests merged in 2025-05, with the labels that each got.

#54 [internal] Add module migration in FAQ and remove SC deletion from afterHelm hook
  .github/workflows/go_checks.yaml
  .github/workflows/go_lint.yaml
  .github/workflows/go_modules_check.yaml
  .github/workflows/go_tests.yaml
  .github/workflows/trivy_check.yaml
  .github/workflows/trivy_image_check.yaml
  docs/README.md
  docs/README_RU.md
  hooks/go/030-remove-sc-and-secrets-on-module-delete/remove-sc-and-secrets-on-module-delete.go
  module.yaml
  oss.yaml
Labels: bug, documentation

#52 Scheduled CVE scan
  .github/workflows/trivy_image_check.yaml
Labels: enhancement

#55 [controller][docs] Fix docs and cis-node templates
  docs/EXAMPLES.md
  docs/EXAMPLES_RU.md
  docs/README.md
  docs/README_RU.md
  templates/cephfs/controller.yaml
  templates/rbd/controller.yaml
Labels: bug

#56 [internal] Fixes in CI, module structure and build
  .github/workflows/build_dev.yml
  .github/workflows/build_prod.yml
  .github/workflows/deploy_dev.yml
  .github/workflows/deploy_prod.yml
  .github/workflows/go_checks.yaml
  .github/workflows/trivy_image_check.yaml
  .werf/choose-edition.yaml
  .werf/consts.yaml
  module.yaml
  openapi/values_ce.yaml
  openapi/values_ee.yaml
  templates/controller/deployment.yaml
  trivy-silent.yaml
  trivy.yaml
  werf.yaml
Labels: enhancement

#58 Fix module version choose
  .werf/bundle.yaml
  .werf/choose-edition.yaml
Labels: bug
